     type Post {
         id: ID!
         title: String!
         content: String!
         user: User
         category: Category!
         likesCount: Int!
         dislikesCount: Int!
         isLiked: Boolean!
         isDisliked: Boolean!    
         isOwner: Boolean!
         createdAt: String!
    }

    type PaginatedPosts {
        posts: [Post!]!
        totalCount: Int!
    }

    type Query {
        # posts: [Post!]!
        # postsByCategory(categoryId: ID!): [Post!]!
        posts(limit: Int!, offset: Int!): PaginatedPosts!
        post(id: ID!): Post 
        postsByCategory(slug: String!, limit: Int!, offset: Int!): PaginatedPosts!
    }
    type Mutation {
        createPost(categoryId: ID!, title: String!, content: String!, userId: ID!): Post
        updatePost(id: ID!, categoryId: ID, title: String, content: String): Post
        deletePost(id: ID!): Boolean

        # Лайки и Дизлайки (возвращают Post для мгновенного обновления кэша)
        addLike(postId: ID!): Post!
        addDislike(postId: ID!): Post!
    }