export const NEWS_ROUTE = '/news'
export const GUIDES_ROUTE = '/guides'
export const POSTS_ROUTE = '/posts'
export const ACCOUNT_INFO_ROUTE = '/account_info'
export const POST_ONE_ROUTE = '/posts/post:id'
