export const NEWS_ROUTE = '/news'
export const GUIDES_ROUTE = '/guides'
export const POSTS_ROUTE = '/posts/:categorySlug'
export const ONE_POST_ROUTE = '/post/:categorySlug/:id'
export const CREATE_NEW_POST = '/psots/create_post'
export const USER_REGISTRATION = '/user_registration'
export const ACCOUNT_INFO_ROUTE = '/account_info'
export const ACCOUNT_SETTINGS_ROUTE = '/account_settings'