type User {
    id: ID!
    login: String!
    email: String!
    avatar: String!
    posts: [Post]
    likes: [Like!]
    dislike: [Dislike!]
}

type AuthResponse {
  accessToken: String!
  refreshToken: String!
  user: User! # Фронтенд сам выберет отсюда только id, login и avatar
}

type Query {
    me: User # Новый роут
    users: [User!]!
    user(id: ID!): User
}

type Mutation {
    # Возвращаем AuthResponse (с двумя токенами)
    loginUser(login: String!, password: String!): AuthResponse!
    # Тоже возвращаем AuthResponse, чтобы сразу авторизовать после регистрации
    addUser(login: String!, password: String!, email: String!, avatar: String): AuthResponse!
    refreshToken(token: String!): AuthResponse!
    deleteUser(id: ID!): Boolean
    updateUser(id: ID!, login: String, password: String, email: String, avatar: String): User
}